from . import school_mixins
from . import school_academic_year
from . import school_board
from . import school_standard
from . import school_section
from . import school_subject
from . import school_staff
from . import school_guardian
from . import school_config
