{
    'name': 'School Exam',
    'version': '19.0.1.0.0',
    'category': 'School Management',
    'summary': 'Exams, CBSE-style grading, marks entry and report cards',
    'author': 'Yashvanth Kumar',
    'license': 'LGPL-3',
    'depends': ['school_core', 'school_admission', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/school_grade_scale_data.xml',
        'views/school_grade_scale_views.xml',
        'views/school_exam_type_views.xml',
        'views/school_exam_views.xml',
        'views/school_exam_result_views.xml',
        'reports/school_report_card_report.xml',
        'reports/school_report_card_template.xml',
        'views/school_report_card_views.xml',
        'views/school_exam_menus.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
