{
    'name': 'School Certificate',
    'version': '19.0.1.0.0',
    'category': 'School Management',
    'summary': 'Transfer Certificate, Bonafide Certificate and ID Card generation',
    'author': 'Yashvanth Kumar',
    'license': 'LGPL-3',
    'depends': ['school_core', 'school_admission', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'reports/school_certificate_report.xml',
        'reports/school_transfer_certificate_template.xml',
        'reports/school_bonafide_certificate_template.xml',
        'reports/school_id_card_report.xml',
        'reports/school_id_card_template.xml',
        'views/school_certificate_views.xml',
        'views/school_id_card_template_views.xml',
        'views/school_certificate_menus.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
