{
    'name': 'School Fees',
    'version': '19.0.1.0.0',
    'category': 'School Management',
    'summary': 'Custom fee structure, invoicing and payment ledger (no accounting integration)',
    'author': 'Yashvanth Kumar',
    'license': 'LGPL-3',
    'depends': ['school_core', 'school_admission', 'mail'],
    'data': [
        'security/school_fees_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/school_fee_head_data.xml',
        'data/ir_cron_data.xml',
        'views/school_fee_head_views.xml',
        'views/school_fee_structure_views.xml',
        'views/school_fee_late_fee_rule_views.xml',
        'views/school_fee_invoice_views.xml',
        'reports/school_fee_receipt_report.xml',
        'reports/school_fee_receipt_template.xml',
        'views/school_fee_payment_views.xml',
        'wizards/school_fee_bulk_invoice_wizard_views.xml',
        'views/school_fees_menus.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
